# Generated by Django 6.0.5 on 2026-05-27 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_record_id', models.CharField(help_text='Original unique row identifier', max_length=100)),
                ('raw_data_payload', models.JSONField(help_text='Original raw un-normalized row for full safety fallback reviews')),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1: Direct Emissions'), ('SCOPE_2', 'Scope 2: Indirect Emissions'), ('SCOPE_3', 'Scope 3: Value Chain Activity')], max_length=10)),
                ('activity_type', models.CharField(help_text='e.g., Diesel, Electricity, Flight, Hotel', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit', models.CharField(max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, help_text='Standardized metrics baseline', max_digits=15)),
                ('cost_in_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('co2_emissions_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUSPICIOUS', 'Flagged Suspicious'), ('FAILED', 'Validation Failed'), ('APPROVED', 'Approved & Immutable')], default='PENDING', max_length=15)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(max_length=50)),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='esg_backend.carbonemissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Procurement'), ('UTILITY', 'Utility Portal Template'), ('TRAVEL', 'Corporate Travel Tracker')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='esg_backend.organization')),
            ],
        ),
        migrations.AddField(
            model_name='carbonemissionrecord',
            name='source_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='esg_backend.datasource'),
        ),
        migrations.AddField(
            model_name='carbonemissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_backend.organization'),
        ),
        migrations.AddIndex(
            model_name='carbonemissionrecord',
            index=models.Index(fields=['organization', 'status'], name='esg_backend_organiz_d6272d_idx'),
        ),
        migrations.AddIndex(
            model_name='carbonemissionrecord',
            index=models.Index(fields=['scope_category'], name='esg_backend_scope_c_481256_idx'),
        ),
    ]
