# Generated by Django 6.0.5 on 2026-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonemissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged Suspicious'), ('APPROVED', 'Approved & Immutable')], default='PENDING', max_length=15),
        ),
    ]
